name: Fetch Frieren Photos

on:
  workflow_dispatch:
  schedule:
    - cron: 0 * * * *

jobs:
  finder:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Prepare Workspace
        run: mkdir -p frieren_photos mail_attachments

      - name: Make Script Executable
        run: chmod +x parser.sh

      - name: Execute Download Script
        run: ./parser.sh

      - name: Filter New Photos
        id: filter_logic
        run: |
          touch last_sent.txt
          
          HAS_NEW=false

          for file in frieren_photos/*; do
            [ -f "$file" ] || continue

            filename=$(basename "$file")

            if ! grep -qxF "$filename" last_sent.txt; then
              cp "$file" mail_attachments/

              echo "$filename" >> last_sent.txt

              HAS_NEW=true
            fi
          done

          if [ "$HAS_NEW" = true ]; then
            echo "send_mail=true" >> $GITHUB_OUTPUT
          else
            echo "send_mail=false" >> $GITHUB_OUTPUT
          fi

      - name: Send Photos via Apple Mail
        if: steps.filter_logic.outputs.send_mail == 'true'
        uses: dawidd6/action-send-mail@42942bc2f8fba4e611b459a018967a6a7c78c68c
        with:
          server_address: smtp.mail.me.com
          server_port: 587
          secure: false
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: "フリーレンの新着写真！"
          to: ${{ secrets.MAIL_USERNAME }}
          from: GitHub Actions Finder <${{ secrets.MAIL_USERNAME }}>
          body: |
            こんにちは！
            
            スクリプトが更新を確認し、フリーレンの新しい写真をダウンロードしました。
            このメールにファイルを添付してお送りします。
            
            よろしくお願いします！
          attachments: mail_attachments/*

      - name: Commit and Push Changes
        if: always()
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@://github.com"
          
          if [ -n "$(git status --porcelain frieren_photos last_sent.txt)" ]; then
            git add frieren_photos/ last_sent.txt
            git commit -m "feat: add new photos and update sent history log"
            git push
          fi
